# Generated by Django 4.1.6 on 2023-02-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2',
            name='oauth_id',
            field=models.CharField(default='', max_length=100, verbose_name='OAuth ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oauth2',
            name='oauth_type',
            field=models.SmallIntegerField(choices=[(0, 'Google'), (1, 'Discord'), (2, 'Github')], verbose_name='Type'),
        ),
    ]
