# Generated by Django 3.2.16 on 2023-02-08 14:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_member_display_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
    ]
