# Generated by Django 4.1.6 on 2023-02-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_oauth2_oauth_id_alter_oauth2_oauth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2',
            name='oauth_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='OAuth ID'),
        ),
    ]
