# Generated by Django 4.1.1 on 2023-01-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access_level',
            field=models.SmallIntegerField(default=0, verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='streamerprofile',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categories'),
        ),
    ]
