# Generated by Django 3.2.16 on 2023-02-08 14:44

from django.db import migrations
import django_countries.fields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
