# Generated by Django 4.1.5 on 2023-02-02 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_access_level_alter_member_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='oAuth2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oauth_type', models.SmallIntegerField(choices=[(0, 'Google')], verbose_name='Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
