# Generated by Django 4.1.6 on 2023-02-04 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_oauth2_oauth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
