# Generated by Django 4.1.5 on 2023-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_oauth2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
