# Generated by Django 4.1.1 on 2023-02-20 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '__first__'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(verbose_name='Submitted On')),
                ('status', models.TextField(choices=[('W', 'WAITING'), ('A', 'APPROVED'), ('R', 'REJECTED')], default='WAITING')),
                ('submission_statement', models.TextField(max_length=1000, verbose_name='Submission Statement')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(verbose_name='Submitted On')),
                ('status', models.TextField(choices=[('W', 'WAITING'), ('A', 'APPROVED'), ('R', 'REJECTED')], default='WAITING')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcasterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(verbose_name='Submitted On')),
                ('status', models.TextField(choices=[('W', 'WAITING'), ('A', 'APPROVED'), ('R', 'REJECTED')], default='WAITING')),
                ('submission_statement', models.TextField(max_length=1000, verbose_name='Submission Statement')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.broadcaster')),
            ],
        ),
    ]
