# Generated by Django 4.1.1 on 2023-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcasterapplication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eventapplication',
            name='id',
        ),
        migrations.RemoveField(
            model_name='streamerapplication',
            name='id',
        ),
        migrations.AddField(
            model_name='broadcasterapplication',
            name='application_id',
            field=models.CharField(default='80461971', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='application_id',
            field=models.CharField(default='69908925', max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='streamerapplication',
            name='application_id',
            field=models.CharField(default='16967794', max_length=9, primary_key=True, serialize=False),
        ),
    ]
