# Generated by Django 4.1.1 on 2023-02-23 11:45

import applications.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_broadcasterapplication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasterapplication',
            name='application_id',
            field=models.CharField(default=applications.util.new_application_id, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='application_id',
            field=models.CharField(default=applications.util.new_application_id, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='streamerapplication',
            name='application_id',
            field=models.CharField(default=applications.util.new_application_id, max_length=9, primary_key=True, serialize=False),
        ),
    ]
