[package]
name = "srr"
version = "0.1.0"
authors = ["Grzegorz <git@Grzegorz.ie>"]
edition = "2021"

[lib]
name = "srr"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.93"
rand = "0.8.5"

[dependencies.pyo3]
version = "0.18.1"
features = ["extension-module"]