# Generated by Django 4.1.6 on 2023-02-02 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('mode', models.CharField(choices=[('I', 'Ingest'), ('R', 'Relay'), ('RR', 'Root Relay')], default='I', max_length=2)),
                ('secret', models.CharField(default=secrets.token_urlsafe, max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StreamAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(default='18fa7c669d5d58cb8fa42952600fa961', max_length=64, validators=[django.core.validators.MinLengthValidator(32)])),
                ('stream', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField()),
                ('list_type', models.CharField(choices=[('B', 'Blacklist'), ('W', 'Whitelist')], default='B', max_length=1)),
                ('ingest_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_server', to='server_manager.server')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('server_list', models.ManyToManyField(to='server_manager.server')),
            ],
        ),
    ]
