# Generated by Django 4.1.1 on 2023-02-16 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='3ae4e96a8335fbd27758d5a320e25b16', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
