# Generated by Django 4.1.1 on 2023-02-23 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='fa0339f254f01cabb496e3ba105676c5', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
