# Generated by Django 4.1.1 on 2023-02-20 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0002_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='9136717a207a7bbfa04b1163f0a36090', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
