# Generated by Django 3.2.16 on 2023-01-29 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0003_alter_streamaccess_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamaccess',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='97f6358fa6a8ef9a27f970f0baf92e30', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
