# Generated by Django 4.1.5 on 2023-01-30 11:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server_manager', '0004_auto_20230129_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='b7ef5942bac6be7159850387838d282f', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField()),
                ('list_type', models.CharField(choices=[('B', 'Blacklist'), ('W', 'Whitelist')], default='B', max_length=1)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
