# Generated by Django 4.1.5 on 2023-01-30 13:01

import django.core.validators
from django.db import migrations, models
import secrets
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0005_alter_streamaccess_key_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('mode', models.CharField(choices=[('I', 'Ingester'), ('R', 'Relay'), ('RR', 'Root Relay')], default='I', max_length=2)),
                ('secret', models.CharField(default=secrets.token_urlsafe, max_length=64, validators=[django.core.validators.MinLengthValidator(3)])),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('live', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='2b9115d931ad4cff9fb6820de0edd7a3', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
