# Generated by Django 4.1.5 on 2023-01-30 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0006_server_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='2403484f1a6c9e3d412fb701e12f38b9', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
