# Generated by Django 4.1.5 on 2023-01-30 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0007_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='server_list',
            field=models.ManyToManyField(to='server_manager.server'),
        ),
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='61a5dc3da9380eae9709ff079d552c95', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
