# Generated by Django 4.1.5 on 2023-01-30 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0009_publisher_ingest_server_alter_server_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='6711413cc45d3f4445caf186bc28e2e6', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
