# Generated by Django 4.1.1 on 2023-01-31 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0010_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='24a2fd1844589492a81224462c2cc5df', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
