# Generated by Django 4.1.1 on 2023-02-02 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0011_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='64dbd40c1ff1ccf236c47003ee7c186d', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
