# Generated by Django 4.1.6 on 2023-02-01 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0011_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='a9287e15dfd18d464a0283f9d7e8ea20', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
