# Generated by Django 4.1.1 on 2023-02-02 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0012_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='0244bf69a908191cdf1c57cb5afa11e6', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
