# Generated by Django 4.1.6 on 2023-02-01 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0012_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='82cdb7a5be5a9cb9d55404dba681053a', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
