# Generated by Django 4.1.6 on 2023-02-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0011_alter_streamaccess_key_remove_streamaccess_member_and_more'),
        ('server_manager', '0013_alter_streamaccess_key'),
    ]

    operations = [
    ]
