# Generated by Django 4.1.6 on 2023-02-01 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0015_alter_streamaccess_key_alter_streamaccess_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='689e8572556d1df5cc2e67069230b689', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
