# Generated by Django 4.1.5 on 2023-02-02 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0016_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='174945a2072cc96a86aceafade9ef225', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
