# Generated by Django 4.1.6 on 2023-02-02 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0017_alter_streamaccess_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamaccess',
            name='key',
            field=models.CharField(default='952388e9f29c1fe5f646e44e36043c6c', max_length=64, validators=[django.core.validators.MinLengthValidator(32)]),
        ),
    ]
