# Generated by Django 4.1.6 on 2023-02-02 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, verbose_name='Category Name')),
                ('description', models.TextField(max_length=256, verbose_name='Brief Description')),
                ('splash_photo', models.ImageField(upload_to='events')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='events', verbose_name='Photograph')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Photograph Description')),
            ],
            options={
                'verbose_name_plural': 'Event Media',
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=64)),
                ('time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.TextField(default='New Event', verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=3096, verbose_name='Description')),
                ('categories', models.ManyToManyField(to='events.category')),
                ('media', models.ManyToManyField(blank=True, to='events.eventmedia')),
                ('showings', models.ManyToManyField(to='events.showing')),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
