# Generated by Django 4.1.1 on 2023-02-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Showing',
            new_name='EventShowing',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
