# Generated by Django 4.1.6 on 2023-02-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='title',
        ),
    ]
