# Generated by Django 4.1.1 on 2023-02-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_event_title_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='primary_media_idx',
            field=models.IntegerField(default=0),
        ),
    ]
