# Generated by Django 4.1.1 on 2023-02-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_primary_media_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventshowing',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
