# Generated by Django 4.1.1 on 2023-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventshowing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
