# Generated by Django 4.1.1 on 2023-02-05 13:27

from django.db import migrations, models
import events.validation


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventmedia',
            name='picture',
        ),
        migrations.AddField(
            model_name='eventmedia',
            name='media',
            field=models.FileField(null=True, upload_to='events', validators=[events.validation.validate_event_media], verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Media Description'),
        ),
    ]
