# Generated by Django 4.1.1 on 2023-02-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showing',
            old_name='date',
            new_name='time',
        ),
    ]
